version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rake
